### PR TITLE
Added Expo 52 Support

### PR DESCRIPTION
**Pull request by akhockey21**
Updated dependencies to work with Expo 52

### CODE REVIEW

**Comment by g-otn** [comment]
Shouldn't `expo` and `@expo/config-plugins` be a peerDependency anyways? The problem (two different expo versions installed) wouldn't happen then.

**Comment by GabrieleMazzola** [comment]
@intent-kacper-cyranowski any hope this will be merged soon?

**Comment by GabrieleMazzola** [comment]
In the meantime, I temporarily solved this issue with 
```
  "pnpm": {
    "overrides": {
      "@expo/config-plugins": "9.0.10",
      "expo": "52.0.11"
    }
  }
```
in my `package.json`

**Comment by aliberski** [comment]
It should be fixed by [this PR](https://github.com/dotintent/react-native-ble-plx/pull/1260). We'll release it in the next version

**Pull request closed without merging**
