### PR TITLE
Added Expo config plugin

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why

With Expo SDK 41 we've rolled out an interface called [config plugins](https://docs.expo.io/guides/config-plugins/) which lets users add native modules that aren't in the Expo Go app to their native cloud builds and locally when [prebuilding](https://expo.fyi/prebuilding).

This is a [highly requested package](https://expo.canny.io/feature-requests/p/bluetooth-api) so I've created the plugin personally.

We’re still working on improving the development experience for config plugins and custom managed workflow, feel free to add any feedback. People won’t be able to use this in an Expo-Go-like-app until we release “Expo Development Client” ([more info](https://blog.expo.io/expo-managed-workflow-in-2021-d1c9b68aa10)). 

# How

- Added a `/plugin` folder and an `app.plugin.js` as the main entry point to the plugin. Plugins must run in at node LTS environments (currently that means 12 and greater), so a custom `tsconfig.json` is used for transpilation.
- The plugin is like a different package that's vendored for versioning purposes. Building is done with `tsc --build plugin` (`yarn build:plugin`).

# Test Plan

I'm not certain how to test this package in the repo, so I did it externally.

- Run `npm pack` in the package
- Install the package in a managed Expo project `yarn add react-native-ble-plx@../react-native-ble-plx/react-native-ble-plx-2.0.2.tgz`
- Then add `react-native-ble-plx` to the plugins array and build the native app locally with `expo prebuild` and `yarn ios`, `yarn android`. We plan to further automate these steps with `expo install` and `expo run` commands.

Modified some values and in the config plugin and updated with `expo prebuild` and `yarn ios`, `yarn android`.

### CODE REVIEW

**Comment by dashcraft** [comment]
Bump?

**Comment by sadilekivan** [comment]
I would really like to try out this way of adding a native package to expo, I cloned the repo, build tsc, and supplied the app.json with a path to the package. Almost thought I got it working, but when running `expo prebuild` I receive `Unexpected token 'export'`. Excuse me if it's intrusive/unfit to ask for advice here, just unsure how to continue now.

**Comment by amsimon** [comment]
Do you need help approving this? We all would love to start using this feature. Thanks.

**Comment by sadilekivan** [comment]
@EvanBacon 

Thanks for the advice, I'm having a problem packing the repo. When I want to get an http link from the green button at git I clone some other repo without the plugin folder (This one to be exact [https://github.com/EvanBacon/react-native-ble-plx.git](https://github.com/EvanBacon/react-native-ble-plx.git)). 

I did try to just copy the link from an urlbar ([https://github.com/EvanBacon/react-native-ble-plx/tree/%40evanbacon/config-plugin/create](https://github.com/EvanBacon/react-native-ble-plx/tree/%40evanbacon/config-plugin/create)) which seems to be the correct one, but it doesnt pack nor install with npm, im guessing the @ and / symbols?

```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json:
https://github.com/EvanBacon/react-native-ble-plx/tree/%40evanbacon/config-plugin/create.
```

I manually downloaded the folder but still cant pack it. I installed yarn but Im still missing `expo-modules`. 

```
$ npm pack react-native-ble-plx--evanbacon-config-plugin-create/

> react-native-ble-plx@2.0.2 prepare C:\Users\Ivan\.workspace\Expo\PoultryScale\react-native-ble-plx--evanbacon-config-plugin-create   
> npm run clean:plugin && npm run build:plugin

> react-native-ble-plx@2.0.2 clean:plugin C:\Users\Ivan\.workspace\Expo\PoultryScale\react-native-ble-plx--evanbacon-config-plugin-create
> expo-module clean plugin

'expo-module' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I looked it up but found `expo-module-scripts` which isnt what it wants I think.

Any clue to what I'm missing? I can run the `expo` command fine, env vars should be okay too. Thanks in advance, I value your feedback.

**Comment by dashcraft** [comment]
@piotrdubiel  @dariuszseweryn  @Cierpliwy is there anything the community can do to get some eyes on this PR?

**Comment by EvanBacon** [comment]
@sadilekivan download this file, change the filename to `react-native-ble-plx-2.0.2.tgz` (removing `.zip`), and install the package in your project.
[react-native-ble-plx-2.0.2.tgz.zip](https://github.com/Polidea/react-native-ble-plx/files/6643209/react-native-ble-plx-2.0.2.tgz.zip)

**Comment by dariuszseweryn** [comment]
I ask you for a little bit more patience. I do not have capacity at the moment to test it out and this repository will most probably start to be maintained by someone else in the following days. 👍

**Comment by luka2i** [comment]
😢😢😢  when?  😢😢😢

**Comment by dashcraft** [comment]
@EvanBacon could you write a blog post on how to fork this repo and build this plugin for expo?
I've tried several times to get it working but I think there's a step in here I'm missing. It just says
not a valid plugin or no plugin found, etc.

**Comment by EvanBacon** [comment]
@dashcraft you can use this out-of-tree solution in the meantime [`@config-plugins/react-native-ble-plx`](https://github.com/EvanBacon/prototype-config-plugins/tree/master/packages/react-native-ble-plx). It's not versioned with the code so YMMV over time, but for now it works great!

**Comment by Spoutnik97** [comment]
@EvanBacon thanks for your great work! It works fine for me !!!
Maybe a fix to the CI could help the repository owner to merge your PR?

**Comment by outinspace** [comment]
Is this PR still needed to use this library with Expo development clients?

**Comment by EvanBacon** [comment]
@outinspace you can use the [out-of-tree plugin](https://www.npmjs.com/package/@config-plugins/react-native-ble-plx) in the meantime (mentioned just two comments before yours https://github.com/dotintent/react-native-ble-plx/pull/842#issuecomment-870244083).

**Comment by Wolfleader101** [comment]
Just wondering when/if this will ever be merged?

**Comment by fabiendem** [comment]
@Wolfleader101 see https://github.com/dotintent/react-native-ble-plx/issues/908#issuecomment-1280663005

**Comment by dashcraft** [comment]
> @Wolfleader101 see [#908 (comment)](https://github.com/dotintent/react-native-ble-plx/issues/908#issuecomment-1280663005)

The issue is that ble-manager doesn't support expo configs at all, so all the work would have to be done again.

The idea that a react native package that can be ported, wouldn't have the configs necessary for the expo is problematic.

**Comment by fabiendem** [comment]
@dashcraft I don't know what to say
https://github.com/dotintent/react-native-ble-plx/ doesn't seem to be maintained anymore, this expo config may never merge, and even if it merges, we will have a Bluetooth library for expo which is not maintained.
https://github.com/innoveit/react-native-ble-manager is maintained for now, so maybe one can do the expo wrapper for it.

**Comment by dominik-czupryna-withintent** [comment]
The library had a support gap but we are currently working on expo prebuild feature support. This PR has become outdated over time so we will make the necessary changes for the latest versions.

**Comment by dominik-czupryna-withintent** [comment]
Updated in https://github.com/dotintent/react-native-ble-plx/pull/1105 and merged

**Pull request closed without merging**
